### ISSUE TITLE
Add API routes

### ISSUE THREAD

**Issue by LupusVII** [Web-Ex-Machina/contao-portfolio#17]
- [x] Add a token system to allow remote websites to fetch portfolio items

- [x] Add a route `/api/portfolio/list`
This route accept the following arguments (as POST)
* `categories` (portfolio categories IDs, can have several IDs)
* `page` (int)
* `limit` (number of items, max is 30)

- [x] Add a route `/api/portfolio/item`
This route accept the following arguments (as POST)
* `id` (int, portfolio item ID)

Feel free to add some suggestions to this new feature!

**Comment by NodokaMurmevent** [comment]
Created the ApiController with the path : 

- /api/portfolio/doc
- /api/portfolio/item/{id}
  - id :  int more than zero 
- /api/portfolio/items/{page}/{limit}?cats[]=1&cats[]=2
  - page : int more than zero
  - limit : int between 1 and 30
  - cats : mandatory array

api only with GET method

 `HTTP_PORTFOLIO_API_KEY` in header or `&key=APIKEY` in request are needed

The key NEED to be added in the setting page in the admin contao, the key is encrypted with Utils:encryption.

Request example with the key in the URL : 

- https://mysite.fr/api/portfolio/items/2/8?key=myKEY
- https://mysite.fr/api/portfolio/item/2?cats[]=1&cats[]=2&key=myKEY

using the encryption service you need to add the parameter : 
//parameters.yml
```yaml
parameters:
    wem_contao_encryption.encryption_key: '%kernel.secret%'
    wem_contao_encryption.truncate_encryption_key: false
```

If needed, you also may need to enable the encryption service : 
```yaml
//services.yml
services:
  WEM\UtilsBundle\Classes\Encryption:
    arguments:
      $secret: '%env(APP_SECRET)%'
      $truncateKey: false
    public: true
```
